# generated by datamodel-codegen:
#   filename:  output_schema.json
#   timestamp: 2023-05-09T17:27:45+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class OutputSchema(BaseModel):
    title: str = Field(..., description='title of the page', title='Title')
    content: str = Field(..., description='content of the page', title='Content')
