"""Update Prompt model schema

Revision ID: 0796c9833cfb
Revises: 120161fe7363
Create Date: 2023-04-04 22:48:50.680316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0796c9833cfb'
down_revision = '120161fe7363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        # Check for the existence of the 'model_name' column before adding it
        table = sa.Table('prompt', sa.MetaData(),
                         autoload=True, autoload_with=op.get_bind())
        if 'model_name' not in table.columns:
            batch_op.add_column(
                sa.Column('model_name', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('model_params', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('model', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('model_params')
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###
