"""Update Prompt model schema

Revision ID: 120161fe7363
Revises: d3349db97548
Create Date: 2023-04-04 22:27:31.540053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '120161fe7363'
down_revision = 'd3349db97548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('evaluation_datasets',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('template',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('variables',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('variables',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('template',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('evaluation_datasets',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
