"""added active_prompt_id to task

Revision ID: 714841ab53d5
Revises: f41d63bdda2d
Create Date: 2023-04-06 13:51:46.269502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714841ab53d5'
down_revision = 'f41d63bdda2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prompt', ['active_prompt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active_prompt_id')

    # ### end Alembic commands ###
