"""empty message

Revision ID: d3349db97548
Revises: f5b1b09462a8
Create Date: 2023-03-26 14:35:45.752141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3349db97548'
down_revision = 'f5b1b09462a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_index('cognito_sub')
        batch_op.drop_column('cognito_sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognito_sub', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index('cognito_sub', ['cognito_sub'], unique=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
